# Permalinks
permalink:        pretty

# Setup
title:            PDX SDARC
tagline:          'Sexual and Domestic Abuse Resource Center'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/

plugins:
  - jekyll-toc
